### AUTH REGISTER
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstName": "Mateo",
  "lastName": "Muñoz",
  "email": "quicenosalom8e8@gmail.com",
  "password": "nexzus",
  "confirmPassword": "nexzus"
}