spring.application.name=ecommerce

# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_sb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=nexzus
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SpringBoot
spring.main.banner-mode=off

